export const GET_MOVIES = 'GET_MOVIES';
export const ADD_MOVIE = 'ADD_MOVIE';
export const UPDATE_MOVIE = 'UPDATE_MOVIE';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const SEARCH_MOVIE = 'SEARCH_MOVIE';

export const CHANGE_ACTIVE_GENRE = 'CHANGE_ACTIVE_GENRE';
export const CHANGE_ACTIVE_SORTING = 'CHANGE_ACTIVE_SORTING';

export const SET_DELETE_MOVIE = 'SET_DELETE_MOVIE';
export const SET_EDIT_MOVIE = 'SET_EDIT_MOVIE';
export const SET_ACTIVE_MOVIE = 'SET_ACTIVE_MOVIE';

export const OPEN_ADD_MOVIE_MODAL = 'OPEN_ADD_MOVIE_MODAL';
export const OPEN_EDIT_MOVIE_MODAL = 'OPEN_EDIT_MOVIE_MODAL';
export const OPEN_DELETE_MOVIE_MODAL = 'OPEN_DELETE_MOVIE_MODAL';
export const OPEN_CONGRATS_MOVIE_MODAL = 'OPEN_CONGRATS_MOVIE_MODAL';
export const CLOSE_ALL_MODALS = 'CLOSE_ALL_MODALS';